#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

name: "kms release"

env:
  GO_VERSION: 1.17

on:
  push:
    tags:
      - "v*"

jobs:
  Publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set ENV vars
        run: |
          TAG=$(git describe --tags --always `git rev-list --tags --max-count=1`)
          echo "IMAGE_TAG"=$TAG >> $GITHUB_ENV
          echo "KMS_IMAGE_PREFIX"=ghcr.io/trustbloc/kms >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push KMS image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/kms-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            ALPINE_VER=3.14
            GO_VER=${{ env.GO_VERSION }}
          push: true
          tags: |
            ${{ env.KMS_IMAGE_PREFIX }}:${{ env.IMAGE_TAG }}
            ${{ env.KMS_IMAGE_PREFIX }}:latest
