#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

FROM nginx:latest
RUN apt-get update && \
    apt-get install iproute2 -y

CMD nginx -g daemon off;